name: windows

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: powershell

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: test5
        run: |
          ./1.build.ps1 test

      - name: test6
        run: |
          ./1.build.ps1 test6

      - name: test2
        run: |
          ./1.build.ps1 test2

      - name: result
        run: |
          Get-Content z.test.log
